<a href="https://colab.research.google.com/github/rogernogueira/caam/blob/main/Grid_PiPE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [104]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.8-cp311-cp311-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.11/dist-packages (from catboost) (0.20.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.11/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.11/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from catboost) (1.15.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.11/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (4.58.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (3.2.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly->catboost) (9.1.2)
Downloading catboost-1.2.8-cp311-cp311-manylinux2014_x86_64.whl (99.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 MB 5.1 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.8

In [105]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import xgboost
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
from sklearn.model_selection import GridSearchCV, StratifiedKFold
import catboost

In [2]:
df  = pd.read_csv('https://gist.githubusercontent.com/rogernogueira/30a55552e6b64f89ab09b552eb93fb05/raw/600f1a01a8cf4c10b8330b4d48ba663f71fae143/heart.csv')

In [37]:
df.isna().sum()

ge                0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ge              918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [13]:
pd.get_dummies(df, columns =['Sex', 'ChestPainType','RestingECG', 'ST_Slope', 'ExerciseAngina'], drop_first=True  )

,ge,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ST_Slope_Flat,ST_Slope_Up,ExerciseAngina_Y
0,40,140,289,0,172,0.0,0,True,True,False,False,True,False,False,True,False
1,49,160,180,0,156,1.0,1,False,False,True,False,True,False,True,False,False
2,37,130,283,0,98,0.0,0,True,True,False,False,False,True,False,True,False
3,48,138,214,0,108,1.5,1,False,False,False,False,True,False,True,False,True
4,54,150,195,0,122,0.0,0,True,False,True,False,True,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,132,1.2,1,True,False,False,True,True,False,True,False,False
914,68,144,193,1,141,3.4,1,True,False,False,False,True,False,True,False,False
915,57,130,131,0,115,1.2,1,True,False,False,False,True,False,True,False,True
916,57,130,236,0,174,0.0,1,False,True,False,False,False,False,True,False,False
917,38,138,175,0,173,0.0,0,True,False,True,False,True,False,False,True,False

In [17]:
df['ChestPainType'].unique()

array(['ATA', 'NAP', 'ASY', 'TA'], dtype=object)

In [19]:
cat_col = ['Sex', 'ChestPainType','RestingECG', 'ST_Slope', 'ExerciseAngina', 'FastingBS']
num_col = ['ge','RestingBP','Cholesterol', 'MaxHR','Oldpeak']

In [21]:
num_pipe = Pipeline([ ('scaler', StandardScaler())])
cat_pipe = Pipeline([ ('encoder', OneHotEncoder(handle_unknown='ignore'))])

In [28]:
preprocess = ColumnTransformer([('num', num_pipe, num_col),
                                ('cat', cat_pipe, cat_col)])

In [29]:
X = df.drop('HeartDisease', axis = 1)
y = df['HeartDisease']

In [31]:
X_train,X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [30]:
xgb_pipe = Pipeline(
    [
        ('prep', preprocess),
        ('xgb', xgboost.XGBClassifier())
    ]
)

In [32]:
xgb_pipe.fit(X_train, y_train)

Pipeline(steps=[('prep',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['ge', 'RestingBP',
                                                   'Cholesterol', 'MaxHR',
                                                   'Oldpeak']),
                                                 ('cat',
                                                  Pipeline(steps=[('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Sex', 'ChestPainType',
                                                   'RestingECG', 'ST_Slope',
                                                   'ExerciseAngina',
                                                   'FastingBS'])])),
                ('xgb',
                 XGBClassifier(base_score=...
                               feature_types=None, gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None, random_state=None, ...))])

In [34]:
y_pred  = xgb_pipe.predict(X_test)

In [38]:
print('Acuracia: ', accuracy_score(y_test, y_pred))
print('Precisão', precision_score(y_test, y_pred))
print('Recall: ', recall_score(y_test, y_pred))
print('AUC: ',roc_auc_score(y_test, y_pred))

Acuracia:  0.8731884057971014
Precisão 0.910828025477707
Recall:  0.8719512195121951
AUC:  0.8734756097560976

In [45]:
rf_pipe = Pipeline(
    [
        ('prep', preprocess),
        ('rf_cls', RandomForestClassifier())
    ]
)

In [47]:
rf_pipe.fit(X_train, y_train)

Pipeline(steps=[('prep',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['ge', 'RestingBP',
                                                   'Cholesterol', 'MaxHR',
                                                   'Oldpeak']),
                                                 ('cat',
                                                  Pipeline(steps=[('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Sex', 'ChestPainType',
                                                   'RestingECG', 'ST_Slope',
                                                   'ExerciseAngina',
                                                   'FastingBS'])])),
                ('rf_cls', RandomForestClassifier())])

In [48]:
y_pred_rf = rf_pipe.predict(X_test)

In [50]:
print('Acuracia: ', accuracy_score(y_test, y_pred_rf))
print('Precisão', precision_score(y_test,y_pred_rf))
print('Recall: ', recall_score(y_test, y_pred_rf))
print('AUC: ',roc_auc_score(y_test, y_pred_rf))

Acuracia:  0.894927536231884
Precisão 0.9192546583850931
Recall:  0.9024390243902439
AUC:  0.8931837979094076

In [81]:
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

In [73]:
params_dist = {
    'xgb__n_estimators': [100, 200, 300],
    #'xgb__learning_rate': [0.01, 0.1, 0.2],
    'xgb__max_depth': [3, 4, 5],
    'xgb__gamma':[0,0.1, 0.3,0.5]
}

In [74]:
grid = GridSearchCV(
    estimator=xgb_pipe,
    param_grid=params_dist,
    cv=cv,
    scoring='roc_auc',
    verbose=2,
    n_jobs=-1
)

In [75]:
grid.fit(X_train, y_train)

Fitting 5 folds for each of 36 candidates, totalling 180 fits

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('prep',
                                        ColumnTransformer(transformers=[('num',
                                                                         Pipeline(steps=[('scaler',
                                                                                          StandardScaler())]),
                                                                         ['ge',
                                                                          'RestingBP',
                                                                          'Cholesterol',
                                                                          'MaxHR',
                                                                          'Oldpeak']),
                                                                        ('cat',
                                                                         Pipeline(steps=[('encoder',
                                                                                          OneHotEncoder(handle_unknown='ignore'))]),
                                                                         ['Sex',
                                                                          'ChestPainType',
                                                                          'Restin...
                                                      max_cat_to_onehot=None,
                                                      max_delta_step=None,
                                                      max_depth=None,
                                                      max_leaves=None,
                                                      min_child_weight=None,
                                                      missing=nan,
                                                      monotone_constraints=None,
                                                      multi_strategy=None,
                                                      n_estimators=None,
                                                      n_jobs=None,
                                                      num_parallel_tree=None,
                                                      random_state=None, ...))]),
             n_jobs=-1,
             param_grid={'xgb__gamma': [0, 0.1, 0.3, 0.5],
                         'xgb__max_depth': [3, 4, 5],
                         'xgb__n_estimators': [100, 200, 300]},
             scoring='roc_auc', verbose=2)

In [76]:
grid.best_params_

{'xgb__gamma': 0.5, 'xgb__max_depth': 4, 'xgb__n_estimators': 100}

In [77]:
best_model = grid.best_estimator_

In [78]:
y_pred = best_model.predict(X_test)

In [79]:
print('Acuracia: ', accuracy_score(y_test, y_pred))
print('Precisão', precision_score(y_test, y_pred))
print('Recall: ', recall_score(y_test, y_pred))
print('AUC: ',roc_auc_score(y_test, y_pred))

Acuracia:  0.8586956521739131
Precisão 0.9032258064516129
Recall:  0.8536585365853658
AUC:  0.8598649825783972

array(['ge', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol',
       'FastingBS', 'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak',
       'ST_Slope'], dtype=object)

In [100]:
params_dist = {
    'rf_cls__n_estimators': [100, 200, 300, 400, 500, ],
    'rf_cls__bootstrap': [True, False],
    'rf_cls__max_depth': [3, 4, 5, 6, 7,8],

}

In [101]:
grid_rf = GridSearchCV(
    estimator=rf_pipe,
    param_grid=params_dist,
    cv=cv,
    scoring='roc_auc',
    verbose=2,
    n_jobs=-1
)

In [102]:
grid_rf.fit(X_train, y_train)

Fitting 5 folds for each of 60 candidates, totalling 300 fits

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('prep',
                                        ColumnTransformer(transformers=[('num',
                                                                         Pipeline(steps=[('scaler',
                                                                                          StandardScaler())]),
                                                                         ['ge',
                                                                          'RestingBP',
                                                                          'Cholesterol',
                                                                          'MaxHR',
                                                                          'Oldpeak']),
                                                                        ('cat',
                                                                         Pipeline(steps=[('encoder',
                                                                                          OneHotEncoder(handle_unknown='ignore'))]),
                                                                         ['Sex',
                                                                          'ChestPainType',
                                                                          'RestingECG',
                                                                          'ST_Slope',
                                                                          'ExerciseAngina',
                                                                          'FastingBS'])])),
                                       ('rf_cls', RandomForestClassifier())]),
             n_jobs=-1,
             param_grid={'rf_cls__bootstrap': [True, False],
                         'rf_cls__max_depth': [3, 4, 5, 6, 7, 8],
                         'rf_cls__n_estimators': [100, 200, 300, 400, 500]},
             scoring='roc_auc', verbose=2)

In [89]:
model_rf  = grid_rf.best_estimator_

In [90]:
y_pred = model_rf.predict(X_test)

In [91]:
print('Acuracia: ', accuracy_score(y_test, y_pred))
print('Precisão', precision_score(y_test, y_pred))
print('Recall: ', recall_score(y_test, y_pred))
print('AUC: ',roc_auc_score(y_test, y_pred))

Acuracia:  0.8913043478260869
Precisão 0.9135802469135802
Recall:  0.9024390243902439
AUC:  0.8887195121951219

In [92]:
grid_rf.best_params_

{'rf_cls__max_depth': 5, 'rf_cls__n_estimators': 300}

In [93]:
rf_pipe2 = Pipeline(
    [
        ('prep', preprocess),
        ('rf_cls', RandomForestClassifier(max_depth=5, n_estimators = 300))
    ]
)

In [94]:
rf_pipe2.fit(X_train, y_train)

Pipeline(steps=[('prep',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['ge', 'RestingBP',
                                                   'Cholesterol', 'MaxHR',
                                                   'Oldpeak']),
                                                 ('cat',
                                                  Pipeline(steps=[('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Sex', 'ChestPainType',
                                                   'RestingECG', 'ST_Slope',
                                                   'ExerciseAngina',
                                                   'FastingBS'])])),
                ('rf_cls',
                 RandomForestClassifier(max_depth=5, n_estimators=300))])

In [95]:
y_pred = rf_pipe2.predict(X_test)

In [96]:
print('Acuracia: ', accuracy_score(y_test, y_pred))
print('Precisão', precision_score(y_test, y_pred))
print('Recall: ', recall_score(y_test, y_pred))
print('AUC: ',roc_auc_score(y_test, y_pred))

Acuracia:  0.8840579710144928
Precisão 0.9074074074074074
Recall:  0.8963414634146342
AUC:  0.8812064459930314

In [106]:
cls = catboost.CatBoostClassifier()

In [107]:
catb_piper = Pipeline(
    [
        ('prep', preprocess),
        ('catb', catboost.CatBoostClassifier())
    ]
)

In [108]:
catb_piper.fit(X_train, y_train)

Learning rate set to 0.008526
0:	learn: 0.6862650	total: 51.8ms	remaining: 51.8s
1:	learn: 0.6790617	total: 65.4ms	remaining: 32.7s
2:	learn: 0.6724127	total: 70.3ms	remaining: 23.4s
3:	learn: 0.6670929	total: 75.3ms	remaining: 18.8s
4:	learn: 0.6612325	total: 79.4ms	remaining: 15.8s
5:	learn: 0.6554049	total: 87.4ms	remaining: 14.5s
6:	learn: 0.6487819	total: 95.4ms	remaining: 13.5s
7:	learn: 0.6421386	total: 104ms	remaining: 12.8s
8:	learn: 0.6364015	total: 112ms	remaining: 12.4s
9:	learn: 0.6299049	total: 136ms	remaining: 13.5s
10:	learn: 0.6258432	total: 137ms	remaining: 12.3s
11:	learn: 0.6209787	total: 153ms	remaining: 12.6s
12:	learn: 0.6150979	total: 155ms	remaining: 11.7s
13:	learn: 0.6087922	total: 165ms	remaining: 11.6s
14:	learn: 0.6034734	total: 167ms	remaining: 11s
15:	learn: 0.5990161	total: 171ms	remaining: 10.5s
16:	learn: 0.5934377	total: 175ms	remaining: 10.1s
17:	learn: 0.5871371	total: 177ms	remaining: 9.64s
18:	learn: 0.5813970	total: 181ms	remaining: 9.33s
19:	learn: 0.5765635	total: 186ms	remaining: 9.14s
20:	learn: 0.5716752	total: 191ms	remaining: 8.9s
21:	learn: 0.5663944	total: 194ms	remaining: 8.63s
22:	learn: 0.5621765	total: 200ms	remaining: 8.51s
23:	learn: 0.5579317	total: 205ms	remaining: 8.35s
24:	learn: 0.5536248	total: 209ms	remaining: 8.14s
25:	learn: 0.5491637	total: 211ms	remaining: 7.9s
26:	learn: 0.5452781	total: 219ms	remaining: 7.88s
27:	learn: 0.5411557	total: 224ms	remaining: 7.78s
28:	learn: 0.5365719	total: 226ms	remaining: 7.58s
29:	learn: 0.5320998	total: 232ms	remaining: 7.51s
30:	learn: 0.5275080	total: 234ms	remaining: 7.33s
31:	learn: 0.5236962	total: 242ms	remaining: 7.31s
32:	learn: 0.5196591	total: 244ms	remaining: 7.15s
33:	learn: 0.5151842	total: 255ms	remaining: 7.25s
34:	learn: 0.5110159	total: 258ms	remaining: 7.12s
35:	learn: 0.5085397	total: 263ms	remaining: 7.04s
36:	learn: 0.5044507	total: 265ms	remaining: 6.9s
37:	learn: 0.5000595	total: 272ms	remaining: 6.89s
38:	learn: 0.4962684	total: 274ms	remaining: 6.76s
39:	learn: 0.4929453	total: 282ms	remaining: 6.78s
40:	learn: 0.4895041	total: 299ms	remaining: 6.99s
41:	learn: 0.4856094	total: 313ms	remaining: 7.13s
42:	learn: 0.4822132	total: 318ms	remaining: 7.09s
43:	learn: 0.4789578	total: 330ms	remaining: 7.16s
44:	learn: 0.4755722	total: 340ms	remaining: 7.21s
45:	learn: 0.4718172	total: 348ms	remaining: 7.22s
46:	learn: 0.4683823	total: 355ms	remaining: 7.19s
47:	learn: 0.4648301	total: 357ms	remaining: 7.08s
48:	learn: 0.4613895	total: 364ms	remaining: 7.06s
49:	learn: 0.4587360	total: 366ms	remaining: 6.95s
50:	learn: 0.4554327	total: 372ms	remaining: 6.92s
51:	learn: 0.4522073	total: 374ms	remaining: 6.82s
52:	learn: 0.4497439	total: 381ms	remaining: 6.81s
53:	learn: 0.4472712	total: 388ms	remaining: 6.79s
54:	learn: 0.4438755	total: 390ms	remaining: 6.7s
55:	learn: 0.4410497	total: 398ms	remaining: 6.7s
56:	learn: 0.4396231	total: 399ms	remaining: 6.61s
57:	learn: 0.4376220	total: 404ms	remaining: 6.57s
58:	learn: 0.4349575	total: 406ms	remaining: 6.48s
59:	learn: 0.4317326	total: 414ms	remaining: 6.48s
60:	learn: 0.4300894	total: 418ms	remaining: 6.43s
61:	learn: 0.4274893	total: 420ms	remaining: 6.35s
62:	learn: 0.4248382	total: 427ms	remaining: 6.35s
63:	learn: 0.4225205	total: 432ms	remaining: 6.31s
64:	learn: 0.4199610	total: 435ms	remaining: 6.25s
65:	learn: 0.4172677	total: 441ms	remaining: 6.24s
66:	learn: 0.4153604	total: 443ms	remaining: 6.17s
67:	learn: 0.4136627	total: 445ms	remaining: 6.1s
68:	learn: 0.4113963	total: 452ms	remaining: 6.1s
69:	learn: 0.4089893	total: 454ms	remaining: 6.04s
70:	learn: 0.4065015	total: 461ms	remaining: 6.03s
71:	learn: 0.4040521	total: 463ms	remaining: 5.97s
72:	learn: 0.4015833	total: 469ms	remaining: 5.95s
73:	learn: 0.3995431	total: 471ms	remaining: 5.89s
74:	learn: 0.3973765	total: 476ms	remaining: 5.87s
75:	learn: 0.3949161	total: 478ms	remaining: 5.81s
76:	learn: 0.3933480	total: 485ms	remaining: 5.81s
77:	learn: 0.3920063	total: 487ms	remaining: 5.75s
78:	learn: 0.3901574	total: 493ms	remaining: 5.75s
79:	learn: 0.3885470	total: 495ms	remaining: 5.69s
80:	learn: 0.3868387	total: 502ms	remaining: 5.69s
81:	learn: 0.3846347	total: 504ms	remaining: 5.64s
82:	learn: 0.3833431	total: 511ms	remaining: 5.64s
83:	learn: 0.3816607	total: 513ms	remaining: 5.59s
84:	learn: 0.3800881	total: 519ms	remaining: 5.59s
85:	learn: 0.3780765	total: 521ms	remaining: 5.54s
86:	learn: 0.3765988	total: 528ms	remaining: 5.54s
87:	learn: 0.3747166	total: 530ms	remaining: 5.49s
88:	learn: 0.3732473	total: 537ms	remaining: 5.49s
89:	learn: 0.3718296	total: 539ms	remaining: 5.45s
90:	learn: 0.3704642	total: 545ms	remaining: 5.45s
91:	learn: 0.3687954	total: 547ms	remaining: 5.4s
92:	learn: 0.3672145	total: 557ms	remaining: 5.43s
93:	learn: 0.3658040	total: 559ms	remaining: 5.39s
94:	learn: 0.3652415	total: 560ms	remaining: 5.34s
95:	learn: 0.3640391	total: 567ms	remaining: 5.34s
96:	learn: 0.3627321	total: 569ms	remaining: 5.3s
97:	learn: 0.3614256	total: 592ms	remaining: 5.45s
98:	learn: 0.3604590	total: 605ms	remaining: 5.5s
99:	learn: 0.3593010	total: 612ms	remaining: 5.5s
100:	learn: 0.3578706	total: 624ms	remaining: 5.55s
101:	learn: 0.3562908	total: 631ms	remaining: 5.55s
102:	learn: 0.3551674	total: 639ms	remaining: 5.56s
103:	learn: 0.3540869	total: 650ms	remaining: 5.6s
104:	learn: 0.3528100	total: 659ms	remaining: 5.62s
105:	learn: 0.3521119	total: 663ms	remaining: 5.59s
106:	learn: 0.3509907	total: 677ms	remaining: 5.65s
107:	learn: 0.3497343	total: 688ms	remaining: 5.68s
108:	learn: 0.3488872	total: 694ms	remaining: 5.67s
109:	learn: 0.3474466	total: 701ms	remaining: 5.67s
110:	learn: 0.3463207	total: 712ms	remaining: 5.7s
111:	learn: 0.3450886	total: 718ms	remaining: 5.7s
112:	learn: 0.3438126	total: 730ms	remaining: 5.73s
113:	learn: 0.3427735	total: 737ms	remaining: 5.73s
114:	learn: 0.3423550	total: 738ms	remaining: 5.68s
115:	learn: 0.3411557	total: 750ms	remaining: 5.71s
116:	learn: 0.3403231	total: 756ms	remaining: 5.7s
117:	learn: 0.3393321	total: 778ms	remaining: 5.82s
118:	learn: 0.3380547	total: 792ms	remaining: 5.86s
119:	learn: 0.3373029	total: 797ms	remaining: 5.84s
120:	learn: 0.3362327	total: 803ms	remaining: 5.83s
121:	learn: 0.3352780	total: 813ms	remaining: 5.85s
122:	learn: 0.3342094	total: 825ms	remaining: 5.88s
123:	learn: 0.3328001	total: 827ms	remaining: 5.84s
124:	learn: 0.3319076	total: 834ms	remaining: 5.84s
125:	learn: 0.3310149	total: 842ms	remaining: 5.84s
126:	learn: 0.3299156	total: 844ms	remaining: 5.8s
127:	learn: 0.3289631	total: 849ms	remaining: 5.78s
128:	learn: 0.3276755	total: 852ms	remaining: 5.75s
129:	learn: 0.3268214	total: 860ms	remaining: 5.75s
130:	learn: 0.3261585	total: 871ms	remaining: 5.78s
131:	learn: 0.3252165	total: 875ms	remaining: 5.75s
132:	learn: 0.3244003	total: 880ms	remaining: 5.74s
133:	learn: 0.3234461	total: 886ms	remaining: 5.73s
134:	learn: 0.3225810	total: 892ms	remaining: 5.71s
135:	learn: 0.3215208	total: 894ms	remaining: 5.68s
136:	learn: 0.3203996	total: 905ms	remaining: 5.7s
137:	learn: 0.3195009	total: 916ms	remaining: 5.72s
138:	learn: 0.3185329	total: 921ms	remaining: 5.7s
139:	learn: 0.3177743	total: 924ms	remaining: 5.68s
140:	learn: 0.3171790	total: 933ms	remaining: 5.68s
141:	learn: 0.3166092	total: 934ms	remaining: 5.64s
142:	learn: 0.3164093	total: 940ms	remaining: 5.63s
143:	learn: 0.3161575	total: 941ms	remaining: 5.59s
144:	learn: 0.3154323	total: 953ms	remaining: 5.62s
145:	learn: 0.3148601	total: 961ms	remaining: 5.62s
146:	learn: 0.3142443	total: 965ms	remaining: 5.6s
147:	learn: 0.3133642	total: 972ms	remaining: 5.6s
148:	learn: 0.3121139	total: 975ms	remaining: 5.57s
149:	learn: 0.3110947	total: 983ms	remaining: 5.57s
150:	learn: 0.3108022	total: 984ms	remaining: 5.53s
151:	learn: 0.3102811	total: 986ms	remaining: 5.5s
152:	learn: 0.3095692	total: 992ms	remaining: 5.49s
153:	learn: 0.3087213	total: 994ms	remaining: 5.46s
154:	learn: 0.3078672	total: 1s	remaining: 5.46s
155:	learn: 0.3068948	total: 1s	remaining: 5.43s
156:	learn: 0.3061571	total: 1.01s	remaining: 5.42s
157:	learn: 0.3054623	total: 1.01s	remaining: 5.39s
158:	learn: 0.3048033	total: 1.02s	remaining: 5.39s
159:	learn: 0.3041841	total: 1.02s	remaining: 5.36s
160:	learn: 0.3037916	total: 1.04s	remaining: 5.4s
161:	learn: 0.3032471	total: 1.04s	remaining: 5.38s
162:	learn: 0.3027301	total: 1.05s	remaining: 5.37s
163:	learn: 0.3020205	total: 1.05s	remaining: 5.34s
164:	learn: 0.3013323	total: 1.06s	remaining: 5.38s
165:	learn: 0.3009292	total: 1.07s	remaining: 5.38s
166:	learn: 0.3004072	total: 1.07s	remaining: 5.36s
167:	learn: 0.2997476	total: 1.08s	remaining: 5.34s
168:	learn: 0.2990750	total: 1.1s	remaining: 5.4s
169:	learn: 0.2982560	total: 1.12s	remaining: 5.46s
170:	learn: 0.2978574	total: 1.12s	remaining: 5.44s
171:	learn: 0.2969718	total: 1.13s	remaining: 5.43s
172:	learn: 0.2963532	total: 1.14s	remaining: 5.47s
173:	learn: 0.2958193	total: 1.15s	remaining: 5.45s
174:	learn: 0.2952741	total: 1.16s	remaining: 5.45s
175:	learn: 0.2946219	total: 1.16s	remaining: 5.44s
176:	learn: 0.2941874	total: 1.17s	remaining: 5.45s
177:	learn: 0.2933183	total: 1.17s	remaining: 5.42s
178:	learn: 0.2928677	total: 1.19s	remaining: 5.46s
179:	learn: 0.2923209	total: 1.19s	remaining: 5.44s
180:	learn: 0.2917943	total: 1.2s	remaining: 5.41s
181:	learn: 0.2913065	total: 1.2s	remaining: 5.4s
182:	learn: 0.2905927	total: 1.21s	remaining: 5.38s
183:	learn: 0.2901038	total: 1.21s	remaining: 5.37s
184:	learn: 0.2893979	total: 1.22s	remaining: 5.38s
185:	learn: 0.2888967	total: 1.24s	remaining: 5.42s
186:	learn: 0.2883732	total: 1.24s	remaining: 5.41s
187:	learn: 0.2877219	total: 1.25s	remaining: 5.41s
188:	learn: 0.2869853	total: 1.26s	remaining: 5.39s
189:	learn: 0.2863491	total: 1.26s	remaining: 5.37s
190:	learn: 0.2860306	total: 1.27s	remaining: 5.4s
191:	learn: 0.2854447	total: 1.28s	remaining: 5.39s
192:	learn: 0.2849706	total: 1.28s	remaining: 5.38s
193:	learn: 0.2841455	total: 1.3s	remaining: 5.39s
194:	learn: 0.2833141	total: 1.3s	remaining: 5.39s
195:	learn: 0.2828386	total: 1.31s	remaining: 5.38s
196:	learn: 0.2821946	total: 1.32s	remaining: 5.37s
197:	learn: 0.2817629	total: 1.32s	remaining: 5.36s
198:	learn: 0.2812270	total: 1.33s	remaining: 5.37s
199:	learn: 0.2807779	total: 1.33s	remaining: 5.34s
200:	learn: 0.2804830	total: 1.35s	remaining: 5.36s
201:	learn: 0.2800181	total: 1.35s	remaining: 5.35s
202:	learn: 0.2796297	total: 1.36s	remaining: 5.33s
203:	learn: 0.2788785	total: 1.37s	remaining: 5.33s
204:	learn: 0.2785331	total: 1.38s	remaining: 5.34s
205:	learn: 0.2778571	total: 1.38s	remaining: 5.33s
206:	learn: 0.2774220	total: 1.39s	remaining: 5.33s
207:	learn: 0.2770475	total: 1.39s	remaining: 5.31s
208:	learn: 0.2765480	total: 1.4s	remaining: 5.3s
209:	learn: 0.2759632	total: 1.4s	remaining: 5.28s
210:	learn: 0.2753334	total: 1.41s	remaining: 5.27s
211:	learn: 0.2747588	total: 1.41s	remaining: 5.25s
212:	learn: 0.2743500	total: 1.41s	remaining: 5.22s
213:	learn: 0.2738454	total: 1.43s	remaining: 5.24s
214:	learn: 0.2736707	total: 1.43s	remaining: 5.22s
215:	learn: 0.2728411	total: 1.44s	remaining: 5.21s
216:	learn: 0.2725163	total: 1.44s	remaining: 5.19s
217:	learn: 0.2720576	total: 1.45s	remaining: 5.18s
218:	learn: 0.2716072	total: 1.45s	remaining: 5.16s
219:	learn: 0.2712619	total: 1.45s	remaining: 5.16s
220:	learn: 0.2708641	total: 1.46s	remaining: 5.13s
221:	learn: 0.2704739	total: 1.47s	remaining: 5.15s
222:	learn: 0.2701634	total: 1.48s	remaining: 5.14s
223:	learn: 0.2698479	total: 1.48s	remaining: 5.13s
224:	learn: 0.2694005	total: 1.48s	remaining: 5.1s
225:	learn: 0.2684110	total: 1.5s	remaining: 5.13s
226:	learn: 0.2678247	total: 1.5s	remaining: 5.12s
227:	learn: 0.2674382	total: 1.51s	remaining: 5.12s
228:	learn: 0.2671945	total: 1.52s	remaining: 5.13s
229:	learn: 0.2667919	total: 1.53s	remaining: 5.12s
230:	learn: 0.2662707	total: 1.53s	remaining: 5.11s
231:	learn: 0.2657411	total: 1.54s	remaining: 5.1s
232:	learn: 0.2653348	total: 1.54s	remaining: 5.08s
233:	learn: 0.2646114	total: 1.57s	remaining: 5.13s
234:	learn: 0.2643053	total: 1.57s	remaining: 5.12s
235:	learn: 0.2637118	total: 1.58s	remaining: 5.12s
236:	learn: 0.2631933	total: 1.59s	remaining: 5.11s
237:	learn: 0.2628237	total: 1.59s	remaining: 5.11s
238:	learn: 0.2624631	total: 1.61s	remaining: 5.12s
239:	learn: 0.2619532	total: 1.61s	remaining: 5.1s
240:	learn: 0.2611703	total: 1.62s	remaining: 5.11s
241:	learn: 0.2605932	total: 1.63s	remaining: 5.11s
242:	learn: 0.2602368	total: 1.64s	remaining: 5.11s
243:	learn: 0.2599333	total: 1.65s	remaining: 5.11s
244:	learn: 0.2594325	total: 1.66s	remaining: 5.11s
245:	learn: 0.2591223	total: 1.67s	remaining: 5.1s
246:	learn: 0.2585690	total: 1.67s	remaining: 5.1s
247:	learn: 0.2579005	total: 1.68s	remaining: 5.09s
248:	learn: 0.2575621	total: 1.69s	remaining: 5.08s
249:	learn: 0.2571559	total: 1.69s	remaining: 5.07s
250:	learn: 0.2568783	total: 1.69s	remaining: 5.05s
251:	learn: 0.2563796	total: 1.7s	remaining: 5.04s
252:	learn: 0.2561730	total: 1.7s	remaining: 5.03s
253:	learn: 0.2557647	total: 1.71s	remaining: 5.02s
254:	learn: 0.2554617	total: 1.71s	remaining: 5.01s
255:	learn: 0.2549730	total: 1.72s	remaining: 4.99s
256:	learn: 0.2547321	total: 1.72s	remaining: 4.98s
257:	learn: 0.2544617	total: 1.72s	remaining: 4.96s
258:	learn: 0.2541304	total: 1.73s	remaining: 4.96s
259:	learn: 0.2537109	total: 1.74s	remaining: 4.94s
260:	learn: 0.2533403	total: 1.74s	remaining: 4.94s
261:	learn: 0.2531588	total: 1.75s	remaining: 4.92s
262:	learn: 0.2528384	total: 1.75s	remaining: 4.91s
263:	learn: 0.2524235	total: 1.75s	remaining: 4.89s
264:	learn: 0.2518313	total: 1.76s	remaining: 4.89s
265:	learn: 0.2513206	total: 1.77s	remaining: 4.88s
266:	learn: 0.2511305	total: 1.78s	remaining: 4.88s
267:	learn: 0.2507810	total: 1.78s	remaining: 4.86s
268:	learn: 0.2504288	total: 1.79s	remaining: 4.86s
269:	learn: 0.2502916	total: 1.79s	remaining: 4.84s
270:	learn: 0.2499675	total: 1.8s	remaining: 4.83s
271:	learn: 0.2495044	total: 1.8s	remaining: 4.82s
272:	learn: 0.2490814	total: 1.8s	remaining: 4.8s
273:	learn: 0.2487222	total: 1.81s	remaining: 4.79s
274:	learn: 0.2482806	total: 1.81s	remaining: 4.77s
275:	learn: 0.2476892	total: 1.82s	remaining: 4.76s
276:	learn: 0.2473420	total: 1.82s	remaining: 4.76s
277:	learn: 0.2468475	total: 1.83s	remaining: 4.74s
278:	learn: 0.2464373	total: 1.83s	remaining: 4.74s
279:	learn: 0.2460658	total: 1.84s	remaining: 4.72s
280:	learn: 0.2456424	total: 1.84s	remaining: 4.72s
281:	learn: 0.2453806	total: 1.85s	remaining: 4.7s
282:	learn: 0.2449610	total: 1.85s	remaining: 4.7s
283:	learn: 0.2445782	total: 1.86s	remaining: 4.69s
284:	learn: 0.2442656	total: 1.86s	remaining: 4.68s
285:	learn: 0.2437808	total: 1.87s	remaining: 4.67s
286:	learn: 0.2435670	total: 1.88s	remaining: 4.66s
287:	learn: 0.2431735	total: 1.88s	remaining: 4.65s
288:	learn: 0.2427223	total: 1.89s	remaining: 4.64s
289:	learn: 0.2423608	total: 1.89s	remaining: 4.62s
290:	learn: 0.2420878	total: 1.89s	remaining: 4.61s
291:	learn: 0.2416837	total: 1.9s	remaining: 4.6s
292:	learn: 0.2413188	total: 1.9s	remaining: 4.58s
293:	learn: 0.2409450	total: 1.91s	remaining: 4.58s
294:	learn: 0.2404714	total: 1.91s	remaining: 4.56s
295:	learn: 0.2403968	total: 1.91s	remaining: 4.54s
296:	learn: 0.2399797	total: 1.92s	remaining: 4.55s
297:	learn: 0.2396683	total: 1.93s	remaining: 4.54s
298:	learn: 0.2392894	total: 1.93s	remaining: 4.53s
299:	learn: 0.2388709	total: 1.94s	remaining: 4.53s
300:	learn: 0.2386543	total: 1.94s	remaining: 4.51s
301:	learn: 0.2383777	total: 1.95s	remaining: 4.5s
302:	learn: 0.2380018	total: 1.95s	remaining: 4.49s
303:	learn: 0.2378155	total: 1.96s	remaining: 4.48s
304:	learn: 0.2375321	total: 1.96s	remaining: 4.46s
305:	learn: 0.2372103	total: 1.96s	remaining: 4.45s
306:	learn: 0.2371369	total: 1.96s	remaining: 4.43s
307:	learn: 0.2367813	total: 1.97s	remaining: 4.42s
308:	learn: 0.2363211	total: 1.98s	remaining: 4.43s
309:	learn: 0.2360855	total: 1.99s	remaining: 4.42s
310:	learn: 0.2356042	total: 1.99s	remaining: 4.42s
311:	learn: 0.2352171	total: 2s	remaining: 4.41s
312:	learn: 0.2350026	total: 2.01s	remaining: 4.41s
313:	learn: 0.2346526	total: 2.02s	remaining: 4.41s
314:	learn: 0.2346351	total: 2.02s	remaining: 4.39s
315:	learn: 0.2343072	total: 2.04s	remaining: 4.41s
316:	learn: 0.2339466	total: 2.05s	remaining: 4.41s
317:	learn: 0.2336038	total: 2.05s	remaining: 4.4s
318:	learn: 0.2331573	total: 2.06s	remaining: 4.4s
319:	learn: 0.2328137	total: 2.07s	remaining: 4.4s
320:	learn: 0.2325775	total: 2.08s	remaining: 4.4s
321:	learn: 0.2321595	total: 2.09s	remaining: 4.39s
322:	learn: 0.2319584	total: 2.09s	remaining: 4.39s
323:	learn: 0.2316778	total: 2.1s	remaining: 4.39s
324:	learn: 0.2312069	total: 2.11s	remaining: 4.38s
325:	learn: 0.2309145	total: 2.12s	remaining: 4.38s
326:	learn: 0.2303938	total: 2.12s	remaining: 4.37s
327:	learn: 0.2299834	total: 2.13s	remaining: 4.37s
328:	learn: 0.2296606	total: 2.14s	remaining: 4.37s
329:	learn: 0.2294290	total: 2.15s	remaining: 4.36s
330:	learn: 0.2291809	total: 2.15s	remaining: 4.36s
331:	learn: 0.2289158	total: 2.17s	remaining: 4.36s
332:	learn: 0.2287999	total: 2.17s	remaining: 4.36s
333:	learn: 0.2285606	total: 2.18s	remaining: 4.35s
334:	learn: 0.2283013	total: 2.19s	remaining: 4.34s
335:	learn: 0.2279964	total: 2.2s	remaining: 4.34s
336:	learn: 0.2274031	total: 2.2s	remaining: 4.33s
337:	learn: 0.2270428	total: 2.21s	remaining: 4.33s
338:	learn: 0.2267365	total: 2.22s	remaining: 4.33s
339:	learn: 0.2265616	total: 2.23s	remaining: 4.33s
340:	learn: 0.2262991	total: 2.23s	remaining: 4.31s
341:	learn: 0.2260591	total: 2.24s	remaining: 4.3s
342:	learn: 0.2255560	total: 2.24s	remaining: 4.29s
343:	learn: 0.2251897	total: 2.25s	remaining: 4.28s
344:	learn: 0.2249893	total: 2.25s	remaining: 4.27s
345:	learn: 0.2247538	total: 2.25s	remaining: 4.26s
346:	learn: 0.2245471	total: 2.26s	remaining: 4.25s
347:	learn: 0.2243523	total: 2.27s	remaining: 4.24s
348:	learn: 0.2241387	total: 2.27s	remaining: 4.23s
349:	learn: 0.2238769	total: 2.27s	remaining: 4.22s
350:	learn: 0.2236429	total: 2.28s	remaining: 4.21s
351:	learn: 0.2231874	total: 2.28s	remaining: 4.2s
352:	learn: 0.2228456	total: 2.29s	remaining: 4.2s
353:	learn: 0.2226502	total: 2.29s	remaining: 4.19s
354:	learn: 0.2225412	total: 2.29s	remaining: 4.17s
355:	learn: 0.2223599	total: 2.32s	remaining: 4.19s
356:	learn: 0.2220962	total: 2.33s	remaining: 4.19s
357:	learn: 0.2217331	total: 2.34s	remaining: 4.19s
358:	learn: 0.2214042	total: 2.35s	remaining: 4.19s
359:	learn: 0.2213908	total: 2.36s	remaining: 4.19s
360:	learn: 0.2211106	total: 2.36s	remaining: 4.18s
361:	learn: 0.2208468	total: 2.37s	remaining: 4.18s
362:	learn: 0.2206051	total: 2.38s	remaining: 4.18s
363:	learn: 0.2203078	total: 2.38s	remaining: 4.17s
364:	learn: 0.2199639	total: 2.39s	remaining: 4.16s
365:	learn: 0.2196168	total: 2.4s	remaining: 4.16s
366:	learn: 0.2191723	total: 2.4s	remaining: 4.15s
367:	learn: 0.2189976	total: 2.42s	remaining: 4.15s
368:	learn: 0.2188683	total: 2.42s	remaining: 4.14s
369:	learn: 0.2187188	total: 2.42s	remaining: 4.12s
370:	learn: 0.2184426	total: 2.43s	remaining: 4.12s
371:	learn: 0.2182137	total: 2.43s	remaining: 4.11s
372:	learn: 0.2179165	total: 2.44s	remaining: 4.09s
373:	learn: 0.2176750	total: 2.45s	remaining: 4.11s
374:	learn: 0.2174250	total: 2.46s	remaining: 4.09s
375:	learn: 0.2169164	total: 2.46s	remaining: 4.09s
376:	learn: 0.2166125	total: 2.47s	remaining: 4.08s
377:	learn: 0.2163469	total: 2.48s	remaining: 4.07s
378:	learn: 0.2161116	total: 2.48s	remaining: 4.06s
379:	learn: 0.2159626	total: 2.48s	remaining: 4.05s
380:	learn: 0.2158238	total: 2.49s	remaining: 4.04s
381:	learn: 0.2156659	total: 2.49s	remaining: 4.03s
382:	learn: 0.2155106	total: 2.49s	remaining: 4.02s
383:	learn: 0.2152661	total: 2.5s	remaining: 4.01s
384:	learn: 0.2148719	total: 2.51s	remaining: 4.01s
385:	learn: 0.2144685	total: 2.52s	remaining: 4.01s
386:	learn: 0.2143648	total: 2.53s	remaining: 4.01s

Pipeline(steps=[('prep',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['ge', 'RestingBP',
                                                   'Cholesterol', 'MaxHR',
                                                   'Oldpeak']),
                                                 ('cat',
                                                  Pipeline(steps=[('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Sex', 'ChestPainType',
                                                   'RestingECG', 'ST_Slope',
                                                   'ExerciseAngina',
                                                   'FastingBS'])])),
                ('catb',
                 <catboost.core.CatBoostClassifier object at 0x7e3d3a6248d0>)])

In [109]:
y_pred  = catb_piper.predict(X_test)

In [110]:
print('Acuracia: ', accuracy_score(y_test, y_pred))
print('Precisão', precision_score(y_test, y_pred))
print('Recall: ', recall_score(y_test, y_pred))
print('AUC: ',roc_auc_score(y_test, y_pred))

Acuracia:  0.8985507246376812
Precisão 0.930379746835443
Recall:  0.8963414634146342
AUC:  0.8990635888501743